version: '3.8'
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_bost
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    network_mode: "host"
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ./run.sh
    logging:
      options:
        max-size: 10m
        max-file: "3"
    network_mode: "host"
